version: "3.7"

services:
  app:
#    build:
#        context: .
#        dockerfile: Dockerfile
    image: kusumalubis/laravel-apache
    container_name: laravel-apps
    ports:
      - "8070:80"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

networks:
    laravel:
        driver: bridge
